### ISSUE TITLE
Deserialize 'Document' into an Object

### ISSUE THREAD

**Issue by gugarosa** [zzzsochi/yadm#22]
Hello, hope everything is alright!

How can I deserialize a 'Document' class?

For example, I did a request and found an 'User' in my database. Nevertheless, I do not want to access every 'Document' attribute and encode a response. I want to decode the whole 'User' document right away and produce a valid response object.

Thank you for your attention,
Gustavo.

**Comment by deterok** [comment]
Hi Gustavo.

Sorry for waiting. All developers of this project are heavily loaded.

This is probably not the most correct way to generate a response.
However, you can get dict from a model using `yadm.serialize.to_mongo` function.

Example:
```python
from pprint import pprint as print
from yadm import Document, fields, testing, serialize


class User(Document):
    first_name = fields.StringField()
    last_name = fields.StringField()
    password = fields.StringField()
    age = fields.IntegerField(choices=range(5, 80))


if __name__ == "__main__":
    user = testing.create_fake(User)
    print(serialize.to_mongo(user))
```
Result: 
```python
{'_id': ObjectId('5cbacc1ba212ad4bebe6fba0'),
 'age': 15,
 'first_name': 'Nicole',
 'last_name': 'Richards', 
 'password': 'y&!0Gu)tA3',  # <-- Oh no! His password leaked!
}
```

**Comment by gugarosa** [comment]
Thank you for your response Vadim, this is exactly what I was looking for!

I agree that it may not be the best method to generate a response as it might leak some private data from the object. Nevertheless, it will come in handy when dealing with some public information.

Thank you again and best regards,
Gusatvo.
